require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/training_resources", type: :request do
  let(:user) { create(:user) }

  before do
    sign_in(user)
  end

  # This should return the minimal set of attributes required to create a valid
  # TrainingResource. As you add validations to TrainingResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { state: 1 }
  }

  let(:invalid_attributes) { { state: "" } }

  describe "GET /index" do
    it "renders a successful response" do
      TrainingResource.create! valid_attributes
      get training_resources_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      training_resource = TrainingResource.create! valid_attributes
      get training_resource_url(training_resource)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_training_resource_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      training_resource = TrainingResource.create! valid_attributes
      get edit_training_resource_url(training_resource)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TrainingResource" do
        expect {
          post training_resources_url, params: { training_resource: valid_attributes }
        }.to change(TrainingResource, :count).by(1)
      end

      it "redirects to the created training_resource" do
        post training_resources_url, params: { training_resource: valid_attributes }
        expect(response).to redirect_to(training_resource_url(TrainingResource.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TrainingResource" do
        expect {
          post training_resources_url, params: { training_resource: invalid_attributes }
        }.to change(TrainingResource, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post training_resources_url, params: { training_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { state: 1 }
      }

      it "updates the requested training_resource" do
        training_resource = TrainingResource.create! valid_attributes
        patch training_resource_url(training_resource), params: { training_resource: new_attributes }
        training_resource.reload
        expect(response).to redirect_to(training_resource_url(training_resource))
      end

      it "redirects to the training_resource" do
        training_resource = TrainingResource.create! valid_attributes
        patch training_resource_url(training_resource), params: { training_resource: new_attributes }
        training_resource.reload
        expect(response).to redirect_to(training_resource_url(training_resource))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        training_resource = TrainingResource.create! valid_attributes
        patch training_resource_url(training_resource), params: { training_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested training_resource" do
      training_resource = TrainingResource.create! valid_attributes
      expect {
        delete training_resource_url(training_resource)
      }.to change(TrainingResource, :count).by(-1)
    end

    it "redirects to the training_resources list" do
      training_resource = TrainingResource.create! valid_attributes
      delete training_resource_url(training_resource)
      expect(response).to redirect_to(training_resources_url)
    end
  end
end
