# Staging deployment configuration
# Deploy to staging server
servers:
  web:
    hosts:
      - staging.skillrx.org

proxy:
  host: staging.skillrx.org
  app_port: 3000
  ssl: true

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Staging environment variables
env:
  secret:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AZURE_STORAGE_ACCOUNT_KEY
    - AZURE_STORAGE_ACCOUNT_NAME
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - SCOUT_KEY
  clear:
    AWS_BUCKET_NAME: skillrx-staging
    AWS_DEFAULT_REGION: us-east-1
    AWS_ENDPOINT_URL: ""  # Empty for real AWS
    AZURE_STORAGE_SHARE_NAME: skillrx-staging-env
    DATA_IMPORT_SOURCE: azure
    LOCALSTACK_DEBUG: "0"
    RAILS_ENV: production
    RAILS_MAX_THREADS: 5
    S3_SKIP_SIGNATURE_VALIDATION: "0"
    SCOUT_APP_NAME: SkillRX Staging
    SOLID_QUEUE_IN_PUMA: true
    WEB_CONCURRENCY: 2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "skillrx_staging_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys_only: true
  keys:
    - ~/.ssh/skillrx_web_staging.pem
