# data structure for language-specific file uploads:
# name: human-readable name for the file, used to store file and then send it
# path: the path where the file is going to be uploaded
# content: the content of the file, which is generated by the XML or text generator
class FileToUpload < Data.define(:name, :path, :content)
end
